### ISSUE TITLE
[Bug]: Withering and Decay practically don't work

### ISSUE THREAD

**Issue by ZiLenTz** [Fuzss/enderzoology#15]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

Current behavior:
- Withering on a bow and Decay on a sword (at level 1) have duration of 00.00 and last for a very brief moment.
- As a result of short debuff duration, it doesn't give them enough time to tick and deal their damages.
- Increasing their levels probably increase the duration as I tried both of them at level 10 which made them last about 1-2 seconds and deal wither damage.

Steps to reproduce:
- Enchant any sword with Decay or any bow with Wither
- Hit anything whether it's player, mob, other entities such as Target Dummy
- Besides, damage from a sword and a bow, there would be no other damage
- Recommended to test it with another player and pay attention to HUD as debuff indicator will appear for a short moment

Expected behavior:
- Both should last enough for them to tick or 5 seconds similar to Flame enchantment
- The damage should be similar to Flame (5 damage over 5 second) or higher
- Alternatively, there should be configs to adjust the duration and damage

**Comment by Fuzss** [comment]
Thanks a lot for the detailed report! Ticks and seconds were confused in the code, this is fixed now for 1.20.4, might consider a backport later.

**Comment by ZiLenTz** [comment]
Thanks for you reply.

Hopefully the fix will be implemented in 1.20.1 version as many mods are still stuck at this version.
So Decay and Wither can be used instead of Fire Aspect and Flame.

**Comment by Fuzss** [comment]
Fixed for 1.20.1.
