### ISSUE TITLE
[Suggestion]: Suggestions for the Fallen Mount

### ISSUE THREAD

**Issue by Nuttar2004** [Fuzss/enderzoology#17]
### Mod Loader (Optional)

⸺

### Suggestion (Required)

Hello author, I have some suggestions for the Fallen Mount.
I hope that after Fallen Mountain is cured, it will be fixed as a vanilla horse and retain its original Horse Armor, Saddle, and attributes such as health, speed, and jumping height.
Also, do you have the idea of giving different items for healing to convert Fallen Mount into a skeleton horse? (However, converting into a skeleton horse might be conflicted to retaining its original attributes, I'm not sure.)

**Comment by Fuzss** [comment]
A cured fallen mount will return to the original horse / donkey / mule that it killed with all original stats. 
For curing you can use golden apples, I don‘t think there need to be other items for that.
