### ISSUE TITLE
[Bug]: Fallen Knights riding Fallen mounts can not move

### ISSUE THREAD

**Issue by hereticalbackpack** [Fuzss/enderzoology#19]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.2

### Minimal Setup (Required)

Yes

### Notes (Required)

Fallen knights that spawn on fallen mounts can not move. They are able to attack but are stuck on the mount and can not move towards the player even if approached. 
To reproduce, go up to any fallen knight on a fallen mount.

### latest.log (Required)

https://gist.github.com/hereticalbackpack/e208f3f36ba14035ec12b6d67cf85372

**Comment by Fuzss** [comment]
Fixed in latest versions.
