### ISSUE TITLE
[Bug]: unable to use it without puzzles lib 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [Fuzss/enderzoology#26]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

latest

### Minimal Setup (Required)

Yes

### Notes (Required)

i cant use it without puzzles lib 1.21.1, but since ur "easy" trilogy mods are not updated for 1.21.1 (easy anvil,magic,shulkerbox), im constricted to use 1.21 version of puzzles lib, are u able as a temp fix, to also port this mod as "1.21" ?, that would fix the issue temporaly until u update all ur mods to 1.21.1

### latest.log (Required)

not needed

**Comment by Fuzss** [comment]
The other mods will come to 1.21.1 soon.
