### ISSUE TITLE
[Crash]:Server crash caused by Fallen Knights attempting to fire arrows

### ISSUE THREAD

**Issue by KorvasSol** [Fuzss/enderzoology#29]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

21.1.1

### Minimal Setup

⸺

### Notes (Required)

1. Fallen Knight exists(with hunter bow)
2. Fallen Knight tries to fire an arrow at a target(Player, wolf, etc)
3. Server Crashes

Notes: This was on a semi modded mc server so it could be a possible conflict with the mod "Skeletal Remains" which adds skeleton variants to the world.

---LOG---

[21:51:55] [Server thread/ERROR]: Encountered an unexpected exception
--
2826 | net.minecraft.class_148: Ticking entity
2827 | at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1025) ~[server-intermediary.jar:?]
2828 | at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
2829 | at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
2830 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
2831 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
2832 | at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2833 | Caused by: java.lang.IllegalArgumentException: Invalid weapon firing an arrow
2834 | at net.minecraft.class_1665.<init>(class_1665.java:116) ~[server-intermediary.jar:?]
2835 | at net.minecraft.class_1665.<init>(class_1665.java:128) ~[server-intermediary.jar:?]
2836 | at net.minecraft.class_1667.<init>(class_1667.java:38) ~[server-intermediary.jar:?]
2837 | at net.minecraft.class_1744.method_7702(class_1744.java:19) ~[server-intermediary.jar:?]
2838 | at net.minecraft.class_1675.method_18813(class_1675.java:179) ~[server-intermediary.jar:?]
2839 | at net.minecraft.class_1547.method_6996(class_1547.java:216) ~[server-intermediary.jar:?]
2840 | at net.minecraft.class_1547.method_7105(class_1547.java:204) ~[server-intermediary.jar:?]
2841 | at fuzs.enderzoology.world.entity.ai.goal.RangedBowEasyAttackGoal.method_6268(RangedBowEasyAttackGoal.java:86) ~[EnderZoology-v21.1.1-1.21.1-Fabric.jar:?]
2842 | at net.minecraft.class_4135.method_6268(class_4135.java:65) ~[server-intermediary.jar:?]
2843 | at net.minecraft.class_1355.method_38849(class_1355.java:112) ~[server-intermediary.jar:?]
2844 | at net.minecraft.class_1355.method_6275(class_1355.java:103) ~[server-intermediary.jar:?]
2845 | at net.minecraft.class_1308.method_6023(class_1308.java:794) ~[server-intermediary.jar:?]
2846 | at net.minecraft.class_1309.method_6007(class_1309.java:2778) ~[server-intermediary.jar:?]
2847 | at net.minecraft.class_1308.method_6007(class_1308.java:572) ~[server-intermediary.jar:?]
2848 | at net.minecraft.class_1588.method_6007(class_1588.java:44) ~[server-intermediary.jar:?]
2849 | at net.minecraft.class_1547.method_6007(class_1547.java:125) ~[server-intermediary.jar:?]
2850 | at net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
2851 | at net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
2852 | at net.minecraft.class_3218.mixinextras$bridge$method_5773$219(class_3218.java) ~[server-intermediary.jar:?]
2853 | at net.minecraft.class_3218.wrapOperation$cke001$porting_lib_entity$preEntityTick(class_3218.java:9807) ~[server-intermediary.jar:?]
2854 | at net.minecraft.class_3218.mixinextras$bridge$wrapOperation$cke001$porting_lib_entity$preEntityTick$220(class_3218.java) ~[server-intermediary.jar:?]
2855 | at net.minecraft.class_3218.wrapOperation$coj000$puzzleslib$tickNonPassenger(class_3218.java:11297) ~[server-intermediary.jar:?]
2856 | at net.minecraft.class_3218.method_18762(class_3218.java:770) ~[server-intermediary.jar:?]
2857 | at net.minecraft.class_1937.method_18472(class_1937.java:498) ~[server-intermediary.jar:?]
2858 | at net.minecraft.class_3218.method_31420(class_3218.java:408) ~[server-intermediary.jar:?]
2859 | at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
2860 | at net.minecraft.class_3218.method_18765(class_3218.java:372) ~[server-intermediary.jar:?]
2861 | at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[server-intermediary.jar:?]
2862 | ... 5 more
2863 | [21:51:55] [Server thread/ERROR]: This crash report has been saved to: /server/crash-reports/crash-2024-09-23_21.51.55-server.txt

### Crash Report (Required)

https://pastebin.com/74C1mibi

**Comment by Fuzss** [comment]
Thanks fixed in v21.1.2.
