### ISSUE TITLE
[Bug]: getting a weird crash with create? Ender Zoology (enderzoology) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by FullMetalMaster** [Fuzss/enderzoology#8]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

have create mod and this mod in the folder 
[crash-2023-07-05_17.39.39-client.txt](https://github.com/Fuzss/enderzoology/files/11962293/crash-2023-07-05_17.39.39-client.txt)
[latest.log](https://github.com/Fuzss/enderzoology/files/11962294/latest.log)

**Comment by Fuzss** [comment]
That's an issue with Create, I'm just the first one to load the problematic class.
